menu:
  gui:
    display: "<dark_blue>Tvé Domovy"
    size: 6
    fill:
      border: GREEN_STAINED_GLASS_PANE
  home-info:
      display: "<yellow><home>"
      lore:
      - ""
      - <gray>Domov <green><home>
      - <gray>Souřadnice <green><x> <y> <z>
      - <gray>Svět <green><world>
      - ""
      - <aqua>Klikni <green>levým <aqua>pro teleport!
      - <aqua>Klikni <red>pravým <aqua>pro nastavení!