menu:
  gui:
    display: "<dark_blue>Veřejné Warpy (<count>)"
    size: 6
    fill:
      border: YELLOW_STAINED_GLASS_PANE
    button:
      previous:
        item: ENDER_CHEST
        name: <green><< <gray><previous_page> Předchozí stránka
        positions:
          row: 6
          col: 1
      close:
        item: BOOK
        name: <green>Zavřít Menu
        positions:
          row: 6
          col: 5
      next:
        item: ENDER_CHEST
        name: <gray>Další stránka <next_page> <green> >>
        positions:
          row: 6
          col: 9
  items:
    buttons:
      open_owner_warps:
        name: "<green>Tvé Warpy"
        icon: BARREL
        positions:
          row: 6
          col: 2
        action: "OPEN_MENU"
        lore:
          - "<gray>Kliknutím otevřeš své warpy.."
  warp-info:
    display: "<yellow><warp>"
    lore:
      - ""
      - <gray>Vlastník <green><owner>
      - <gray>Svět <green><world>
      - ""
      - <white>Klikni pro teleport!